Try separate lockfile for flakes/neovim-unpackaged-plugins
There was some kind of nonsense like

    error: cannot fetch input 'path:.flakes/neorimv-unpackaged-plugins?[...]
    because it uses a relative path

Found various things on forums which suggest subflake locking is a mess.
No idea if this will help with it or not.